let stock = [
    {
        id: 1,
        nombre:"Nike Air Force 1",
        marca:"Nike",
        precio:"$290",
        precioReal:290,
        imagen:"./imagenes/zapatilla-nike-airforce1.jpeg",
    },
    {
        id: 2,
        nombre:"Nike Air Max 90 Futura",
        marca:"Nike",
        precio:"$312",
        precioReal:312,
        imagen:"./imagenes/zapatilla-nike-airmax90.jpeg",
    },
    {
        id: 3,
        nombre:"Jordan Air XXXVII",
        marca:"Jordan",
        precio:"$430",
        precioReal:430,
        imagen:"./imagenes/zapatilla-jordan-airxxxvii.jpeg",
    },
    {
        id: 4,
        nombre:"Jordan Air 4 Retro",
        marca:"Jordan",
        precio:"$495",
        precioReal:495,
        imagen:"./imagenes/zapatilla-jordan-air4retro.jpeg",
    },
    {
        id: 5,
        nombre:"Adidas Superstar",
        marca:"Adidas",
        precio:"$160",
        precioReal:160,
        imagen:"./imagenes/zapatilla-adidas-superstar.jpeg",
    },
    {
        id: 6,
        nombre:"Adidas Ozelia",
        marca:"Adidas",
        precio:"$145",
        precioReal:145,
        imagen:"./imagenes/zapatilla-adidas-ozelia.jpeg",
    },
    {
        id: 7,
        nombre:"Puma Slipstream",
        marca:"Puma",
        precio:"$215",
        precioReal:215,
        imagen:"./imagenes/zapatilla-puma-slipstream.jpeg",
    },
    {
        id: 8,
        nombre:"Puma Rs-X Triple",
        marca:"Puma",
        precio:"$186",
        precioReal:186,
        imagen: "./imagenes/zapatilla-puma-rsxtriple.jpeg",
    },
    {
        id: 9,
        nombre:"Vans Sk8 Hi",
        marca:"Vans",
        precio:"$168",
        precioReal:168,
        imagen: "./imagenes/zapatilla-vans-sk8hi.jpeg",
    },
    {
        id: 10,
        nombre:"Vans Old Skool",
        marca:"Vans",
        precio:"$180",
        precioReal:180,
        imagen:"./imagenes/zapatilla-vans-oldskool.jpeg",
    },
    {
        id: 11,
        nombre:"Fila Acd Mid",
        marca:"Fila",
        precio:"$160",
        precioReal:160,
        imagen: "./imagenes/zapatilla-fila-acdmid.jpeg",
    },
    {
        id: 12,
        nombre:"Fila Oakmont Sl",
        marca:"Fila",
        precio:"$125",
        precioReal:125,
        imagen: "./imagenes/zapatilla-fila-oakmontsl.jpeg",
    },
]